#
# Jas Strokus - Personal Website
#

name: Jas Strokus
description: Software Engineer @ Microsoft | Cyber Operations | AI/ML

avatar: https://avatars.githubusercontent.com/u/32867544?v=4

# Social links
footer-links:
  email: jasstrokus8@gmail.com
  github: Jacob-Strokus
  linkedin: jacob-strokus

# Site URL
url: https://jacob-strokus.github.io
baseurl: ""

permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
